### PR TITLE
Laravel 11 support

### PR DESCRIPTION
**Pull request by abr4xas**
- drop laravel 8
- added types

### CODE REVIEW

**Comment by markwalet** [comment]
Thanks for your PR, I have a few requests:

Can you keep the indentation on the composer.json file the same? I prefer 4 spaces.

Can you also remove Laravel 8 from the test matrix in Github actions?

Thanks in advance

**Comment by abr4xas** [comment]
Hey @markwalet please let me know if this works :D

**Comment by markwalet** [comment]
It looks like the test matrix wasn't updated completely correct. Missing a new testbench version and it looks like we need to drop php 8.1 support for Laravel 11.

For inspiration you can look at this PR: https://github.com/markwalet/laravel-changelog/pull/54/files

Do you have time to take a look at this? Otherwise I'll fix the PR myself. Thanks for contributing!

**Comment by Lexian-droid** [comment]
Hello, has this update gone anywhere? I know I'm only one person, but I'm working on a project that I'd like to use this in.

**Comment by markwalet** [comment]
It seems like @abr4xas is not responding unfortunately. I'll take a look myself today 👍

**Comment by markwalet** [comment]
Closed in favor of #12, released in [v1.7.0](https://github.com/markwalet/laravel-packagist/releases/tag/v1.7.0)

**Comment by abr4xas** [comment]
> It seems like @abr4xas is not responding unfortunately. I'll take a look myself today 👍

Hey, I'm sorry... Having some issues with other things... Thanks for taking care of this.

**Pull request closed without merging**
